server {
    listen 80;
    server_name 81.71.139.177;

    root /opt/airquality/air-quality-frontend/dist;
    index index.html;

    location /api {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
